In [1]:
import numpy as np
import pandas as pd

In [2]:
np.__version__

'1.21.5'

In [3]:
df = pd.read_csv(r'C:\Users\Johnm\Desktop\self development\Data Science\Courses\zoomcamp\Datasets\data.csv')

In [4]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [5]:
df.shape

(11914, 16)

In [6]:
Car_Makes = df.groupby('Make')
Car_Models = Car_Makes['Model']
Car_Models.nunique()

Make
Acura            18
Alfa Romeo        1
Aston Martin     12
Audi             34
BMW              39
Bentley          18
Bugatti           1
Buick            20
Cadillac         30
Chevrolet        63
Chrysler         19
Dodge            33
FIAT              5
Ferrari          14
Ford             51
GMC              30
Genesis           1
HUMMER            2
Honda            21
Hyundai          22
Infiniti         38
Kia              16
Lamborghini       6
Land Rover       11
Lexus            46
Lincoln          16
Lotus             5
Maserati          8
Maybach           3
Mazda            31
McLaren           4
Mercedes-Benz    40
Mitsubishi       22
Nissan           32
Oldsmobile       18
Plymouth         10
Pontiac          20
Porsche          12
Rolls-Royce      10
Saab              8
Scion             8
Spyker            1
Subaru           16
Suzuki           16
Tesla             1
Toyota           39
Volkswagen       31
Volvo            26
Name: Model, dtype: int64

In [7]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [8]:
df['Engine Cylinders'].mean()

5.628828677213059

In [9]:
df['Engine Cylinders'].median()

6.0

In [10]:
df['Engine Cylinders'].mode()

0    4.0
Name: Engine Cylinders, dtype: float64

In [11]:
df['Engine Cylinders'].fillna(value=4.0, inplace=True)

In [12]:
df['Engine Cylinders'].median()

6.0

In [13]:
car_Makes = df.groupby('Make')
Lotus_Cars = car_Makes.get_group('Lotus')
X = Lotus_Cars.loc[:, ['Engine HP', 'Engine Cylinders']].drop_duplicates()
X

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [14]:
df.loc[df.Make == "Lotus", ['Engine HP', 'Engine Cylinders']].drop_duplicates()

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [15]:
X = X.to_numpy()
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [16]:
X_T = X.T
XTX = np.dot(X_T, X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [17]:
XTX_inverse = np.linalg.inv(XTX)

In [18]:
y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]
a = np.dot(XTX_inverse, X_T)

In [19]:
w = np.dot(a, y)
w

array([  4.59494481, -63.56432501])